### ISSUE TITLE
我不知道为什么 我得 component 貌似没有值一样 ，一直再跳404

### ISSUE THREAD

**Issue by 160nothelp** [guyan0319/go-admin#9]
![image](https://user-images.githubusercontent.com/39042836/93513141-fec4c200-f957-11ea-86d3-b1bb954c4aa7.png)

**Comment by 160nothelp** [comment]
![image](https://user-images.githubusercontent.com/39042836/93513464-77c41980-f958-11ea-9a8b-2b2c087359a3.png)
我是把code 放进去得，也没有报错

**Comment by guyan0319** [comment]
服务端接口返回的接口是什么？
